<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 4 Week 04 | Course Name</title>
  <meta name="description" content="Description about Course/Book." />
  <meta name="generator" content="bookdown 0.24 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 4 Week 04 | Course Name" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Description about Course/Book." />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 4 Week 04 | Course Name" />
  
  <meta name="twitter:description" content="Description about Course/Book." />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  <link rel="shortcut icon" href="assets/dasl_favicon.ico" type="image/x-icon" />
<link rel="prev" href="week-03.html"/>
<link rel="next" href="about-the-authors.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  background-color: #f8f8f8; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="assets/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<a href="http://jhudatascience.org/"><img src="https://jhudatascience.org/images/dasl.png" style=" width: 80%; padding-left: 40px; padding-top: 8px; vertical-align: top "</a>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>About this Course</a>
<ul>
<li class="chapter" data-level="0.1" data-path="index.html"><a href="index.html#available-course-formats"><i class="fa fa-check"></i><b>0.1</b> Available course formats</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="week-01.html"><a href="week-01.html"><i class="fa fa-check"></i><b>1</b> Week 01</a>
<ul>
<li class="chapter" data-level="1.1" data-path="week-01.html"><a href="week-01.html#introduction"><i class="fa fa-check"></i><b>1.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="week-01.html"><a href="week-01.html#welcome-to-regression-models"><i class="fa fa-check"></i><b>1.1.1</b> Welcome to Regression Models</a></li>
<li class="chapter" data-level="1.1.2" data-path="week-01.html"><a href="week-01.html#some-basics"><i class="fa fa-check"></i><b>1.1.2</b> Some Basics</a></li>
<li class="chapter" data-level="1.1.3" data-path="week-01.html"><a href="week-01.html#syllabus"><i class="fa fa-check"></i><b>1.1.3</b> Syllabus</a></li>
<li class="chapter" data-level="1.1.4" data-path="week-01.html"><a href="week-01.html#data-science-specialization-community-site"><i class="fa fa-check"></i><b>1.1.4</b> Data Science Specialization Community Site</a></li>
<li class="chapter" data-level="1.1.5" data-path="week-01.html"><a href="week-01.html#where-to-get-more-advanced-material"><i class="fa fa-check"></i><b>1.1.5</b> Where to get more advanced material</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="week-01.html"><a href="week-01.html#introduction-to-regression-and-least-squares"><i class="fa fa-check"></i><b>1.2</b> Introduction to regression and least squares</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="week-01.html"><a href="week-01.html#introduction-to-regression"><i class="fa fa-check"></i><b>1.2.1</b> Introduction to Regression</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="week-01.html"><a href="week-01.html#linear-least-squares"><i class="fa fa-check"></i><b>1.3</b> Linear least squares</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="week-01.html"><a href="week-01.html#notations-and-background"><i class="fa fa-check"></i><b>1.3.1</b> Notations and background</a></li>
<li class="chapter" data-level="1.3.2" data-path="week-01.html"><a href="week-01.html#linear-least-squares-1"><i class="fa fa-check"></i><b>1.3.2</b> Linear Least Squares</a></li>
<li class="chapter" data-level="1.3.3" data-path="week-01.html"><a href="week-01.html#linear-least-squares-coding-example"><i class="fa fa-check"></i><b>1.3.3</b> Linear Least Squares Coding Example</a></li>
<li class="chapter" data-level="1.3.4" data-path="week-01.html"><a href="week-01.html#mathematical-details-optional"><i class="fa fa-check"></i><b>1.3.4</b> Mathematical Details (Optional)</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="week-01.html"><a href="week-01.html#regression-to-the-mean"><i class="fa fa-check"></i><b>1.4</b> Regression to the Mean</a></li>
<li class="chapter" data-level="1.5" data-path="week-01.html"><a href="week-01.html#practical-r-exercises-in-swirl"><i class="fa fa-check"></i><b>1.5</b> Practical R Exercises in swirl</a></li>
<li class="chapter" data-level="1.6" data-path="week-01.html"><a href="week-01.html#week-1-quiz"><i class="fa fa-check"></i><b>1.6</b> Week 1 Quiz</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="week-02.html"><a href="week-02.html"><i class="fa fa-check"></i><b>2</b> Week 02</a>
<ul>
<li class="chapter" data-level="2.1" data-path="week-02.html"><a href="week-02.html#statistical-linear-regression-models"><i class="fa fa-check"></i><b>2.1</b> Statistical linear regression models</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="week-02.html"><a href="week-02.html#statistical-linear-regression-models-1"><i class="fa fa-check"></i><b>2.1.1</b> Statistical Linear Regression Models</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="week-02.html"><a href="week-02.html#residuals"><i class="fa fa-check"></i><b>2.2</b> Residuals</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="week-02.html"><a href="week-02.html#optional-reading-how-to-derive-r-squared"><i class="fa fa-check"></i><b>2.2.1</b> Optional reading How to derive R squared:</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="week-02.html"><a href="week-02.html#inference-in-regression"><i class="fa fa-check"></i><b>2.3</b> Inference in regression</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="week-02.html"><a href="week-02.html#prediction"><i class="fa fa-check"></i><b>2.3.1</b> Prediction</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="week-02.html"><a href="week-02.html#for-the-project"><i class="fa fa-check"></i><b>2.4</b> For the project</a></li>
<li class="chapter" data-level="2.5" data-path="week-02.html"><a href="week-02.html#practical-r-exercises-in-swirl-1"><i class="fa fa-check"></i><b>2.5</b> Practical R Exercises in swirl</a></li>
<li class="chapter" data-level="2.6" data-path="week-02.html"><a href="week-02.html#week-2-quiz"><i class="fa fa-check"></i><b>2.6</b> Week 2 Quiz</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="week-03.html"><a href="week-03.html"><i class="fa fa-check"></i><b>3</b> Week 03</a>
<ul>
<li class="chapter" data-level="3.1" data-path="week-03.html"><a href="week-03.html#multi-variable-regression"><i class="fa fa-check"></i><b>3.1</b> Multi-variable regression</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="week-03.html"><a href="week-03.html#how-to-get-the-coefficients-derivation-of-formulas"><i class="fa fa-check"></i><b>3.1.1</b> How to get the coefficients, derivation of formulas</a></li>
<li class="chapter" data-level="3.1.2" data-path="week-03.html"><a href="week-03.html#results"><i class="fa fa-check"></i><b>3.1.2</b> Results</a></li>
<li class="chapter" data-level="3.1.3" data-path="week-03.html"><a href="week-03.html#example-with-two-variables-simple-linear-regression"><i class="fa fa-check"></i><b>3.1.3</b> Example with two variables, simple linear regression</a></li>
<li class="chapter" data-level="3.1.4" data-path="week-03.html"><a href="week-03.html#the-general-case"><i class="fa fa-check"></i><b>3.1.4</b> The general case</a></li>
<li class="chapter" data-level="3.1.5" data-path="week-03.html"><a href="week-03.html#examples-with-multiple-variables"><i class="fa fa-check"></i><b>3.1.5</b> Examples with multiple-variables</a></li>
<li class="chapter" data-level="3.1.6" data-path="week-03.html"><a href="week-03.html#interpretation-of-coefficients"><i class="fa fa-check"></i><b>3.1.6</b> Interpretation of coefficients</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="week-03.html"><a href="week-03.html#multi-variable-regression-tips-and-tricks"><i class="fa fa-check"></i><b>3.2</b> Multi-variable regression tips and tricks</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="week-03.html"><a href="week-03.html#dummy-variables-are-smart"><i class="fa fa-check"></i><b>3.2.1</b> Dummy variables are smart</a></li>
<li class="chapter" data-level="3.2.2" data-path="week-03.html"><a href="week-03.html#summary-of-the-insectsprays-example"><i class="fa fa-check"></i><b>3.2.2</b> Summary of the InsectSprays example</a></li>
<li class="chapter" data-level="3.2.3" data-path="week-03.html"><a href="week-03.html#exploring-the-models-in-r"><i class="fa fa-check"></i><b>3.2.3</b> Exploring the models in R</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="week-03.html"><a href="week-03.html#adjustment"><i class="fa fa-check"></i><b>3.3</b> Adjustment</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="week-03.html"><a href="week-03.html#adjustment-examples"><i class="fa fa-check"></i><b>3.3.1</b> Adjustment Examples</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="week-03.html"><a href="week-03.html#residuals-again"><i class="fa fa-check"></i><b>3.4</b> Residuals again</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="week-03.html"><a href="week-03.html#examples-in-r"><i class="fa fa-check"></i><b>3.4.1</b> Examples in R</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="week-03.html"><a href="week-03.html#model-selection"><i class="fa fa-check"></i><b>3.5</b> Model selection</a></li>
<li class="chapter" data-level="3.6" data-path="week-03.html"><a href="week-03.html#practical-r-exercises-in-swirl-2"><i class="fa fa-check"></i><b>3.6</b> Practical R Exercises in swirl</a></li>
<li class="chapter" data-level="3.7" data-path="week-03.html"><a href="week-03.html#week-3-quiz"><i class="fa fa-check"></i><b>3.7</b> Week 3 Quiz</a></li>
<li class="chapter" data-level="3.8" data-path="week-03.html"><a href="week-03.html#optional-practice-exercise-in-regression-modeling"><i class="fa fa-check"></i><b>3.8</b> (OPTIONAL) Practice exercise in regression modeling</a></li>
<li class="chapter" data-level="3.9" data-path="week-03.html"><a href="week-03.html#you-are-being-asked-to-participate-in-a-research-experiment-with-the-purpose-of-better-understanding-how-people-analyze-data.-if-you-complete-this-quiz-you-are-giving-your-consent-to-participate-in-the-study.-this-quiz-involves-a-short-data-analysis-that-gives-you-a-chance-to-practice-the-regression-concepts-you-have-learned-so-far.-we-anticipate-that-this-will-take-about-15-minutes-to-complete.-you-will-be-receiving-feedback-on-your-work-immediately-after-submission.-for-this-reason-we-ask-that-you-do-not-post-on-the-forums-about-this-quiz-to-maintain-the-integrity-of-this-experiment.-thank-you-for-helping-us-learn-more-about-data-science--brian-roger-jeff"><i class="fa fa-check"></i><b>3.9</b> You are being asked to participate in a research experiment with the purpose of better understanding how people analyze data. If you complete this quiz, you are giving your consent to participate in the study. This quiz involves a short data analysis that gives you a chance to practice the regression concepts you have learned so far. We anticipate that this will take about 15 minutes to complete. You will be receiving feedback on your work immediately after submission. For this reason, we ask that you do not post on the forums about this quiz to maintain the integrity of this experiment. Thank you for helping us learn more about data science! -Brian, Roger, Jeff</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="week-04.html"><a href="week-04.html"><i class="fa fa-check"></i><b>4</b> Week 04</a>
<ul>
<li class="chapter" data-level="4.1" data-path="week-04.html"><a href="week-04.html#glm"><i class="fa fa-check"></i><b>4.1</b> GLM</a></li>
<li class="chapter" data-level="4.2" data-path="week-04.html"><a href="week-04.html#logistic-regression"><i class="fa fa-check"></i><b>4.2</b> Logistic Regression</a></li>
<li class="chapter" data-level="4.3" data-path="week-04.html"><a href="week-04.html#poisson-regression"><i class="fa fa-check"></i><b>4.3</b> Poisson Regression</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="week-04.html"><a href="week-04.html#data-count"><i class="fa fa-check"></i><b>4.3.1</b> Data count</a></li>
<li class="chapter" data-level="4.3.2" data-path="week-04.html"><a href="week-04.html#poisson-regression-1"><i class="fa fa-check"></i><b>4.3.2</b> Poisson Regression</a></li>
<li class="chapter" data-level="4.3.3" data-path="week-04.html"><a href="week-04.html#linear-vs.-poisson-regression"><i class="fa fa-check"></i><b>4.3.3</b> Linear vs. Poisson regression</a></li>
<li class="chapter" data-level="4.3.4" data-path="week-04.html"><a href="week-04.html#how-should-we-handle-rates-and-proportions"><i class="fa fa-check"></i><b>4.3.4</b> How should we handle rates and proportions?</a></li>
<li class="chapter" data-level="4.3.5" data-path="week-04.html"><a href="week-04.html#more-information"><i class="fa fa-check"></i><b>4.3.5</b> More information</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="week-04.html"><a href="week-04.html#hodgepodge"><i class="fa fa-check"></i><b>4.4</b> Hodgepodge</a></li>
<li class="chapter" data-level="4.5" data-path="week-04.html"><a href="week-04.html#practical-r-exercises-in-swirl-3"><i class="fa fa-check"></i><b>4.5</b> Practical R Exercises in swirl</a></li>
<li class="chapter" data-level="4.6" data-path="week-04.html"><a href="week-04.html#week-4-quiz"><i class="fa fa-check"></i><b>4.6</b> Week 4 Quiz</a></li>
<li class="chapter" data-level="4.7" data-path="week-04.html"><a href="week-04.html#course-project-1"><i class="fa fa-check"></i><b>4.7</b> Course Project</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="about-the-authors.html"><a href="about-the-authors.html"><i class="fa fa-check"></i>About the Authors</a></li>
<li class="chapter" data-level="5" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>5</b> References</a></li>
<li class="divider"></li>
<p style="text-align:center;"> <a href="https://github.com/jhudsl/OTTR_Template" target="blank" > This content was published with</a> <a href="https://bookdown.org/" target="blank"> bookdown by:</a> </p>
<p style="text-align:center;"> <a href="http://jhudatascience.org/"> The Johns Hopkins Data Science Lab </a></p>
<p style="text-align:center; font-size: 12px;"> <a href="https://github.com/rstudio4edu/rstudio4edu-book/"> Style adapted from: rstudio4edu-book </a> <a href ="https://creativecommons.org/licenses/by/2.0/"> (CC-BY 2.0) </a></p>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Course Name</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<head>
  <meta name="viewport" content="width=device-width,minimum-scale=1.0,maximum-scale=1.0,initial-scale=1.0">
  <!--script src="https://kit.fontawesome.com/6a26f47516.js"></script-->
  <!--<script src="assets/hideOutput.js"></script>-->
  <link href="assets/style.css" rel="stylesheet">
</head>



<div class="hero-image-container">
  <img class= "hero-image" src= "https://github.com/jhudsl/OTTR_Template/raw/main/assets/dasl_thin_main_image.png">
</div>
<div id="week-04" class="section level1" number="4">
<h1><span class="header-section-number">Chapter 4</span> Week 04</h1>
<div id="glm" class="section level2" number="4.1">
<h2><span class="header-section-number">4.1</span> GLM</h2>
<p>Generalized linear models (GLMs) were a great advance in statistical modeling. The original manuscript with the GLM framework was from <a href="https://www.jstor.org/stable/2344614">Nelder and Wedderburn</a> in 1972 in the Journal of the Royal Statistical Society. The <a href="https://books.google.com/books/about/Generalized_Linear_Models_Second_Edition.html?id=h9kFH2_FfBkC">McCullagh and Nelder book</a> is the famous standard treatise on the subject.</p>
<p>Recall linear models. Linear models are the most useful applied statistical technique. However, they are not without their limitations. Additive response models don’t make much sense if the response is discrete, or strictly positive. Additive error models often don’t make sense, for example, if the outcome has to be positive. Transformations, such as taking a cube root of a count outcome, are often hard to interpret.In addition, there is value in modeling the data on the scale that it was collected. Particularly interpretable transformations, natural logarithms in specific, are not applicable for negative or zero values. The generalized linear model is family of models that includes linear models. By extending the family, it handles many of the issues with linear models, but at the expense of some complexity and loss of some of the mathematical tidiness. A GLM involves three components:
* An exponential family model for the response.
* A systematic component via a linear predictor.
* A link function that connects the means of the response to the linear predictor.
The three most famous cases of GLMs are: linear models, binomial and binary regression and Poisson regression. We will go through the GLM model specification and likelihood for all three. For linear models, we have developed them previously. The next two modules will be devoted to binomial and Poisson regression. We will only focus on the most popular and useful link functions.</p>
<p>In this section, we are transitioning from linear additive response models to the broader class of generalized linear models (GLMs). While linear models are immensely useful in applied statistics, they have limitations, especially when dealing with certain types of data. GLMs address some of these challenges, but they may sacrifice some mathematical elegance that linear models offer. Linear models assume additivity, which can be challenging to apply to binary data. Considering binary data as additive might lead to awkward interpretations of the error structure. Additionally, when dealing with strictly positive data, the assumption of additive Gaussian errors can be problematic as it allows for positive mass on negative values. While this might not be an issue in some cases, it becomes problematic if the normal distribution assigns a significant positive probability to negative values, contradicting the known positivity of the response. Transformations are a common strategy to handle strictly positive data. For example, taking the natural logarithm is often used, providing interpretability to the coefficients. However, other transformations, like the arcsine or square root transformation for binomial data, can compromise interpretability. One reason to consider generalized linear models is to avoid the need for transformations and to work directly with the scale in which the data was recorded. GLMs can respect the inherent characteristics of the data, especially when dealing with binary outcomes. The natural log transformation is frequently used, but has challenges when applied to negative or zero values, leading to the development of alternative methods. Generalized linear models were introduced in a 1972 paper by Nelder and Wedderburn, a seminal work in the field of statistics that has been widely read by PhD statisticians. GLMs provide a versatile framework for addressing the limitations of linear models and handling various types of response variables.</p>
<p>A generalized linear model (GLM) comprises three essential components:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Distribution (Random Component):</strong> The randomness in the model is described by a specific family of distributions known as the exponential family. This family includes various distributions like normal, binomial, and Poisson. The choice of the distribution depends on the nature of the response variable.</p></li>
<li><p><strong>Systematic Component (Linear Predictor):</strong> This component involves the linear predictor, which is the part of the model being estimated. This component corresponds to what we modeled in linear models, where the systematic component was the linear combination of covariates with their coefficients.</p></li>
<li><p><strong>Link Function:</strong> The link function connects the linear predictor to the distribution of the response variable from the exponential family. It essentially transforms the linear predictor into a scale that makes sense for the chosen distribution.</p></li>
</ol>
<p>Suppose we assume that the response variable <span class="math inline">\(Y_i \sim N(\mu_i, \sigma^2)\)</span> is normally distributed with mean <span class="math inline">\(\mu\)</span>. We define the linear predictor to be <span class="math inline">\(\eta_i = \sum_{k=1}^p X_{ik} \beta_k\)</span>, and the link function as <span class="math inline">\(g\)</span>, identity link function, so that <span class="math inline">\(g(\mu) = \eta\)</span> and <span class="math inline">\(\mu_i = \eta_i\)</span>. This yields the same likelihood model as our additive error Gaussian linear model <span class="math display">\[Y_i = \sum_{k=1}^p X_{ik} \beta_k + \epsilon_{i}\]</span>
where <span class="math inline">\(\epsilon_i \stackrel{iid}{\sim} N(0, \sigma^2)\)</span>.</p>
<p>To summarize, in this case:
- <strong>Distribution:</strong> The exponential family is represented by the normal distribution.
- <strong>Systematic Component (Linear Predictor):</strong> The linear predictor, denoted as η (eta), is defined as the sum of covariates (xi) multiplied by their coefficients (beta): ηi = ∑(xi * beta).
- <strong>Link Function:</strong> For simplicity, we can choose the identity link function, which directly connects the linear predictor (η) to the mean (Mu) of the normal distribution. This link function implies that Mu is exactly equal to the linear predictor: Mu = η.</p>
<p>The GLM framework allows us to extend the modeling approach beyond linear models by incorporating different distributions, systematic components, and link functions tailored to the characteristics of the response variable.</p>
<p>Let’s delve into logistic regression, perhaps the most useful variation of generalized linear models when dealing with binary data (0s and 1s). Since binary outcomes don’t conform to a normal distribution, we employ a Bernoulli distribution, assuming that our outcomes (Y) follow this distribution. In a Bernoulli distribution, we model the probability of a head (or success) for each observation. This probability is represented by <span class="math inline">\(E[Y_i]=\mu_i\)</span>, where the linear predictor remains the sum of covariates multiplied by their coefficients<span class="math inline">\(\eta_i = \sum_{k=1}^p X_{ik} \beta_k\)</span>. The link function used in logistic regression is the logistic link function, which transforms the probability of success (<span class="math inline">\(\mu\)</span>) into the log odds (log of the odds ratio). <span class="math inline">\(g(\mu) = \eta = \log\left( \frac{\mu}{1 - \mu}\right)\)</span>.Mathematically, this link function is expressed as the natural logarithm of the odds: <span class="math inline">\(g(\mu) = \eta = \log\left( \frac{\mu}{1 - \mu}\right)\)</span>. The logistic link function connects the linear predictor (<span class="math inline">\(η\)</span>) to the log odds. To go from the log odds back to the probability (<span class="math inline">\(\mu\)</span>), we use the inverse of the logistic link function. The inverse logistic function, sometimes referred to as the “logit,” is given by:</p>
<p><span class="math display">\[ 
\mu_i = \frac{\exp(\eta_i)}{1 + \exp(\eta_i)} ~~~\mbox{and}~~~
1 - \mu_i = \frac{1}{1 + \exp(\eta_i)}
\]</span></p>
<p>It’s important to note that this transformation applies to the mean or probability of success (<span class="math inline">\(\mu\)</span>) rather than directly transforming the binary outcomes (Y) themselves. This distinction is a key aspect of generalized linear models, where the focus is on modeling the underlying probabilities or means associated with the observed outcomes. Given the information the likelihood is:
<span class="math display">\[
\prod_{i=1}^n \mu_i^{y_i} (1 - \mu_i)^{1-y_i}
= \exp\left(\sum_{i=1}^n y_i \eta_i \right)
\prod_{i=1}^n (1 + \eta_i)^{-1}
\]</span>
It’s through this likelihood that parameter estimates are optimized by maximizing it.</p>
<p>Let’s discuss another example, Poisson regression. Poisson distribution is suitable for count data, which is often unbounded and positive. The Poisson regression assumes that the response variable Y follows a Poisson distribution with the expected value <span class="math inline">\(\mu_i\)</span>. The linear predictor is again the sum of covariates multiplied by their coefficients, <span class="math inline">\(\eta_i = \sum_{k=1}^p X_{ik} \beta_k\)</span>. The log link function is commonly used in Poisson regression, <span class="math inline">\(g(\mu) = \eta = \log(\mu)\)</span>. Recall that <span class="math inline">\(e^x\)</span> is the inverse of <span class="math inline">\(\log(x)\)</span> so that <span class="math inline">\(\mu_i = e^{\eta_i}\)</span>. The inverse of the natural logarithm is applied to go from the mean (<span class="math inline">\(\mu\)</span>) to the linear predictor (<span class="math inline">\(η\)</span>). Thus, the likelihood is
<span class="math display">\[
\prod_{i=1}^n (y_i !)^{-1} \mu_i^{y_i}e^{-\mu_i}
\propto \exp\left(\sum_{i=1}^n y_i \eta_i - \sum_{i=1}^n \mu_i\right)
\]</span>
The likelihood function for Poisson regression is formulated based on this distribution and the linear predictor. In generalized linear models, the parameters are estimated by maximizing the likelihood function. This is akin to finding roots or solutions of equations, similar to least squares in linear regression.</p>
<p>All models achieve their maximum at the root of the so called normal equations
<span class="math display">\[
0=\sum_{i=1}^n \frac{(Y_i - \mu_i)}{Var(Y_i)}W_i
\]</span>
where <span class="math inline">\(W_i\)</span> are the derivative of the inverse of the link function.</p>
<p>The MLE equation for generalized linear models, presented above, involves weights and variances in the denominator, emphasizing that the fitting process is a bit more complex than least squares. While these details are interesting from a statistical perspective, for practical purposes and interpretation of generalized linear models, understanding the conceptual framework, link functions, and likelihood is often sufficient. It’s important to note that for cases like Poisson and binomial, the variance is not constant across observations, unlike the linear model case. In the Poisson case, the variance of a Poisson distribution equals its mean. Therefore, in this scenario, the Poisson distribution has a variance that differs by <span class="math inline">\(i\)</span>. This assumption in modeling can be verified. For instance, if you have Poisson data with multiple observations at the same covariance level, the means should be equal. Consequently, the variances of these observations should be approximately equal to the mean. If your data doesn’t demonstrate this pattern, it poses an issue. This is a crucial and practical consideration in generalized linear models, where modeling assumptions often impose a constraint on the relationship between the mean and variance. However, this relationship may not hold in your specific dataset.</p>
<p>To address this issue, there is a method involving a more flexible variance model, albeit at the cost of sacrificing some generalized linear model assumptions. Standard options include quasi-Poisson and quasi-binomial distributions, which are available in statistical languages fitting generalized linear models. These quasi versions offer a more flexible variant structure, accommodating data that deviates from the typical GLM variant structure.</p>
<p>Moving on to the fitting process, it’s essential to note that GLMs require iterative optimization, unlike linear models, which allow for straightforward solutions through linear algebra. Consequently, program failures may occur, especially in cases like binary regression with numerous zeros or ones. Before delving into specific cases, such as Poisson and Binomial, it’s crucial to understand that these equations need iterative solutions. Although we won’t cover the full spectrum of GLMs, the process involves solving equations iteratively. For instance, if you wish to obtain the predicted response, you would multiply the estimated coefficients (<span class="math inline">\(\hat \beta\)</span>) by the regressors, yielding the predictive response. It’s important to recognize that this response will be on the log-odds scale for logistic regression or the log scale for Poisson regression. To align it with the original data scale, a conversion to the natural scale is necessary. For example, if you’re modeling coin flips and you obtain regression coefficients to predict responses, those predictions will be on the log-odds scale. To bring them back to the scale of coin flips (binary outcomes between zero or one), you’ll need to invert the log-odds. The coefficients are interpreted similarly to linear regression coefficients, representing the expected change in the response for a unit change in the regressors, with other regressors held constant. However, this interpretation is now done on the scale of the linear predictor: log-odds for the binomial case and log-mean for the Poisson case. Though the interpretation is slightly more complex, the benefit lies in modeling the data on its natural scale without transforming the outcome.</p>
<p>In terms of inference, you lose the convenience of closed-form normal inferences and t-distributions. However, statisticians have determined the appropriate distributions for comparing coefficients and obtaining p-values through the GLM output. The testing and interpretation of coefficients remain similar to linear regression, but the underlying mathematics is more involved. It’s essential to note that these results are based on asymptotics, requiring larger sample sizes. In cases with small sample sizes, p-values may not be applicable.</p>
<p>This overview provides a glimpse into GLMs. In the upcoming sections, the focus will shift to the two crucial cases: binomial and Poisson regression, specifically logistic regression for binary outcomes.</p>
</div>
<div id="logistic-regression" class="section level2" number="4.2">
<h2><span class="header-section-number">4.2</span> Logistic Regression</h2>
<p>Binary GLMs come from trying to model outcomes that can take only two values. Some examples include: survival or not at the end of a study, winning versus losing of a team and success versus failure of a treatment or product. Often these outcomes are called Bernoulli outcomes, from the Bernoulli distribution named after the famous probabilist and mathematician.</p>
<p>If we happen to have several exchangeable binary outcomes for the same level of covariate values, then that is binomial data and we can aggregate the 0’s and 1’s into the count of 1’s. As an example, imagine if we sprayed insect pests with 4 different pesticides and counted whether they died or not. Then for each spray, we could summarize the data with the count of dead and total number that were sprayed and treat the data as binomial rather than Bernoulli.</p>
<p>In this section, the focus is on scenarios where the outcome is a binary random variable, taking values of zero or one. Such situations arise frequently in various analyses, such as survival studies where individuals are either alive or deceased at the study’s conclusion, or in sports analytics, where wins or losses are recorded. The goal is to model the data as a series of coin flips, where the probability of success depends on a set of covariates. When dealing with collections of zeros and ones with a constant success probability and independence, the total number of successes or failures follows a binomial distribution. Binary logistic regression is employed to handle binomial random variables in the special case where the covariate is constant. Here we will cover two cases: binary and binomial, with the focus initially on the binary case. To illustrate, a motivating example is presented using a dataset organized by Jeff Leak, an instructor in the data science specialization.</p>
<div class="sourceCode" id="cb230"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb230-1"><a href="week-04.html#cb230-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">&quot;https://raw.githubusercontent.com/B7M/Course_data/main/ravensData.csv&quot;</span></span>
<span id="cb230-2"><a href="week-04.html#cb230-2" aria-hidden="true" tabindex="-1"></a>              , <span class="at">destfile=</span><span class="st">&quot;ravensData.csv&quot;</span>,<span class="at">method=</span><span class="st">&quot;auto&quot;</span>)</span>
<span id="cb230-3"><a href="week-04.html#cb230-3" aria-hidden="true" tabindex="-1"></a>ravensData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;ravensData.csv&quot;</span>)</span>
<span id="cb230-4"><a href="week-04.html#cb230-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ravensData)</span></code></pre></div>
<pre><code>##   ravenWinNum ravenWin ravenScore opponentScore
## 1           1        W         24             9
## 2           1        W         38            35
## 3           1        W         28            13
## 4           1        W         34            31
## 5           1        W         44            13
## 6           0        L         23            24</code></pre>
<p>The dataset involves the Ravens’ football team, where wins and losses are coded as ones and zeros, respectively. The analysis explores the extent to which the Ravens’ score predicts their winning outcomes. Linear regression is not suitable for this type of data. Attempting to model the probability of a Ravens win as a linear progression would not accurately capture the underlying relationships. While fitting binary data with a linear model is sometimes a preliminary step, it is typically followed by more appropriate models like logistic regression. The potential issues with fitting binary data using linear regression include:
* $ RW_i = b_0 + b_1 RS_i + e_i $
* <span class="math inline">\(RW_i\)</span> - 1 if a Ravens win, 0 if not
* <span class="math inline">\(RS_i\)</span> - Number of points Ravens scored
* <span class="math inline">\(b_0\)</span> - probability of a Ravens win if they score 0 points
* <span class="math inline">\(b_1\)</span> - increase in probability of a Ravens win for each additional point
* <span class="math inline">\(e_i\)</span> - residual variation due</p>
<p>While it’s not the worst thing to fit binary data with linear regression, especially for quick analyses, a preferable approach is to model the odds. In the context of binary outcomes, such as whether the Ravens win, the goal is to model the probability of winning as if it were a series of coin flips. The success probability varies from game to game based on factors like the points the Ravens score. The odds, denoted as the probability over one minus the probability, capture this relationship. The odds can be converted back to probability and vice versa. To quantify the odds, the log odds, also known as the logit, which is introduced as the logarithm of the odds the model is placed on the logit scale. Logistic regression is preferred over linear regression due to the clear violation of linear regression assumptions and the potential inaccuracies in inferences. To draw a connection between the two, linear regression models can be expressed as the expected value of the outcome being a linear relationship. In the case of binary outcomes, the expected value is the probability, highlighting the transition from linear to logistic regression. The logistic regression model involves predicting the log odds, allowing for a more appropriate representation of binary data.
The expected value of a fair coin is 0.5, and instead of directly modeling the expected value of the outcome in logistic regression, the approach is to model the expected value, which is the probability, using the equation exp(the linear regression) over 1 + exp(the linear regression). When this equation is inverted, it results in the log of the odds being the linear regression relationship. In binary generalized linear models, particularly in logistic regression, the data is treated as a series of coin flips with changing success probabilities related to covariates. The log of the odds, also known as the logit, is crucial in this modeling process.</p>
<p>The function that goes backward from the log of the odds to the probability is referred to as the xbit, and <span class="math inline">\(\frac{e^a}{1 + e^a}\)</span> represents this inversion. The clever aspect of generalized linear models lies in not directly placing the model on the scale but recognizing the dependence on a probability distribution, which, in turn, is influenced by the success probability that is connected to regressors.</p>
<p>Interpreting logistic regression is straightforward. <span class="math display">\[ \log\left(\frac{\rm{Pr}(RW_i | RS_i, b_0, b_1 )}{1-\rm{Pr}(RW_i | RS_i, b_0, b_1)}\right) = b_0 + b_1 RS_i \]</span>
If the Ravens score is zero, the log odds (<span class="math inline">\(b_0\)</span>) represent the log odds of a Ravens win. The probability of winning can then be calculated using <span class="math inline">\(\frac{e^{b_0}}{1 + e^{b_0}}\)</span>. However, an imperfect aspect arises when b0 is estimated to be non-zero, despite the team not being able to win with zero points. The slope coefficient (b1) is interpreted as the increase or decrease in the log odds of the probability associated with a one-unit increase in the regression variable (in this case, a one-point increase in score). If we exponentiate the difference on the log scale in logistic regression, we obtain a ratio on the original scale. Exponentiating <span class="math inline">\(e^{b_1}\)</span> results in <span class="math inline">\(e^{b_1}\)</span> being the ratio of the odds, comparing the odds of the Ravens winning for a one-point increase in the score. While there may not be multiple regressors in this particular example, the extension to cases with multiple covariates is direct. The interpretation remains consistent with holding the other regression variables fixed, just like in linear regression. In logistic regression, everything is interpreted under the assumption that other covariates are constant. For instance, if additional covariates, such as whether it was a home or away game, were present, <span class="math inline">\(e^{b_1}\)</span> would represent the odds ratio of a Ravens win for a one-unit increase in the score, holding the status of the game (home or away) constant. The interpretability of logistic regression coefficients is straightforward due to the logarithmic function, which allows the inversion of additive effects into ratios. This interpretation in terms of ratios is convenient and aligns well with how people naturally discuss relationships.</p>
<p>A brief historical note on odds: It originates from the concept of a fair game. Consider a scenario where you flip a coin with a success probability p, winning X dollars if it lands heads, and losing Y dollars if it lands tails. To make the game fair, the expected earnings (winning given heads minus losing given tails) should be equal to zero. Solving for fairness leads to the relationship <span class="math inline">\(\frac{Y}{X} = \frac{p}{1 - p}\)</span>. This equation implies that odds can be seen as how much one would be willing to pay for a p probability of winning a dollar. In summary, the concept of odds is deeply rooted in the idea of a fair game, where <span class="math inline">\(\frac{Y}{X} = \frac{p}{1 - p}\)</span> when X is set to 1. This ratio determines how much one would be willing to pay for a certain probability of winning a dollar. For instance, at a horse track, odds like 10 to 1 indicate that if you bet a dollar and the horse wins, you receive $10. The setting of horse betting probabilities adapts as bets come in, reflecting a balance of money in and out to ensure the house neither wins nor loses. Over time, the aggregate odds from betting often serve as a fairly accurate representation of the percentage of times a horse wins.</p>
<p>Casinos or tracks make money by taking a fee for every bet, ensuring they are financially neutral regardless of the outcome. This fee ensures that the house is guaranteed to win, making the phrase “the house wins” quite literal. The complexity of the betting system involves various factors, but the basic principle remains: the house sets up odds to be financially neutral and takes a small fee from each bet.</p>
<p>Run this in RStudio which is a demonstration using the manipulate package in R, logistic regression curves are visualized with varying values of beta0 (intercept) and beta1 (slope). At the time of developing this course, the manipulate package was not available in OTTR. However, the code is provided for students to run in RStudio.</p>
<div class="sourceCode" id="cb232"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb232-1"><a href="week-04.html#cb232-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(manipulate)</span>
<span id="cb232-2"><a href="week-04.html#cb232-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="dv">10</span>, <span class="dv">10</span>, <span class="at">length =</span> <span class="dv">1000</span>)</span>
<span id="cb232-3"><a href="week-04.html#cb232-3" aria-hidden="true" tabindex="-1"></a><span class="fu">manipulate</span>(</span>
<span id="cb232-4"><a href="week-04.html#cb232-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">plot</span>(x, <span class="fu">exp</span>(beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> x) <span class="sc">/</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(beta0 <span class="sc">+</span> beta1 <span class="sc">*</span> x)), </span>
<span id="cb232-5"><a href="week-04.html#cb232-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>),</span>
<span id="cb232-6"><a href="week-04.html#cb232-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">beta1 =</span> <span class="fu">slider</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="at">step =</span> .<span class="dv">1</span>, <span class="at">initial =</span> <span class="dv">2</span>),</span>
<span id="cb232-7"><a href="week-04.html#cb232-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">beta0 =</span> <span class="fu">slider</span>(<span class="sc">-</span><span class="dv">2</span>, <span class="dv">2</span>, <span class="at">step =</span> .<span class="dv">1</span>, <span class="at">initial =</span> <span class="dv">0</span>)</span>
<span id="cb232-8"><a href="week-04.html#cb232-8" aria-hidden="true" tabindex="-1"></a>    )</span></code></pre></div>
<p>The logistic regression curve resembles an ‘s’ shape, and changes in beta1 result in alterations in the curve’s shape—becoming more peaked for higher values and flipping around for negative values. The beta0 parameter shifts the curve left or right along the x-axis. If the x-axis represents regressors with zeros and ones, R attempts to find the logistic curve that best aligns with the associated probabilities. The principle behind this is maximum likelihood estimation. The logistic regression model, represented as <span class="math inline">\(\frac{e^{(\beta_0 + \beta_1x)}}{1 + e^{(\beta_0 + \beta_1x)}}\)</span>, is used to convert the logistic curve back to the probability scale.</p>
<p>Essentially, logistic regression aims to find the best-fitting curve by adjusting <span class="math inline">\(\beta_0 ,\beta_1\)</span> values. The fitted function captures the logistic regression model on the probability scale. This visualization helps illustrate the underlying process of logistic regression and how R optimizes the logistic curve to match the observed data probabilities.</p>
<p>Now that we have examined the logistics regression curves, let’s explore the outcomes when we apply these curves to our Ravens data. To do this, you use the GLM function to feed the Ravens data.</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="week-04.html#cb233-1" aria-hidden="true" tabindex="-1"></a>logRegRavens <span class="ot">&lt;-</span> <span class="fu">glm</span>(ravensData<span class="sc">$</span>ravenWinNum <span class="sc">~</span> ravensData<span class="sc">$</span>ravenScore,<span class="at">family=</span><span class="st">&quot;binomial&quot;</span>)</span>
<span id="cb233-2"><a href="week-04.html#cb233-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logRegRavens)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = ravensData$ravenWinNum ~ ravensData$ravenScore, 
##     family = &quot;binomial&quot;)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.7575  -1.0999   0.5305   0.8060   1.4947  
## 
## Coefficients:
##                       Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept)           -1.68001    1.55412  -1.081     0.28
## ravensData$ravenScore  0.10658    0.06674   1.597     0.11
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 24.435  on 19  degrees of freedom
## Residual deviance: 20.895  on 18  degrees of freedom
## AIC: 24.895
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>The <code>glm</code> function function is similarly to the <code>lm</code> function, with the response variable on the left side of the tilde and the predictors on the right side. The key difference here is that we need to specify “family equals binomial” to inform the <code>glm</code> function that we are working with binary data (0,1). If dealing with count data or real binomial data, a sample size would also need to be specified. By default, for binomial and binary cases, the <code>glm</code> function assumes the logistic link function, which is appropriate.</p>
<p>When reviewing the summary output, it mirrors the format used for the <code>lm</code> function. The coefficients for the Ravens data are displayed, such as -1.68 and 0.1 for the intercept and Ravens coefficient, respectively. On the Logit scale, it’s important to examine whether the coefficients are close to zero for variables like the Ravens score, and on the exponentiated scale, whether they are close to one. The summary includes standard errors, Z values, and P values, which are interpreted similarly to a linear model, recognizing the differences in interpretation.</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="week-04.html#cb235-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(ravensData<span class="sc">$</span>ravenScore,logRegRavens<span class="sc">$</span>fitted,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span><span class="st">&quot;blue&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Score&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Prob Ravens Win&quot;</span>)</span>
<span id="cb235-2"><a href="week-04.html#cb235-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.68</span> <span class="sc">+</span> <span class="fl">0.1</span><span class="sc">*</span>x)<span class="sc">/</span>(<span class="dv">1</span> <span class="sc">+</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">1.68</span> <span class="sc">+</span> <span class="fl">0.1</span><span class="sc">*</span>x)),<span class="at">add=</span><span class="cn">TRUE</span>,<span class="at">col=</span><span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-5-1.png" width="672" />
The fitted curve represents the predicted responses converted back to the probability scale. R calculates this by substituting the x values associated with the coefficients, multiplying them by the respective coefficients, adding the estimated intercept, and applying the logistic function. The result is the probability values. It’s crucial to note that the displayed fitted S curve is only a portion, as the component where the data are observed is restricted. The S curve depicted earlier has a starting point at one, resembling a curve that ascends and eventually descends, concluding at 0.4 instead of zero. This signifies the actual curve fitting the data, although the displayed fitted values only show a portion of it. Exponentiating the Ravens coefficients yields 0.1864 for the intercept and 1.1125 for the score, indicating an 11% increase in the probability of winning for each additional point the Ravens score. Interpreting this logistic regression coefficient involves assessing the odds ratios. Confidence intervals for these coefficients are easily obtained using the <code>confint</code> operator. The preferred method for viewing these intervals on the exponentiated scale involves using the x function to exponentiate the two endpoints.</p>
<div class="sourceCode" id="cb236"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb236-1"><a href="week-04.html#cb236-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(logRegRavens<span class="sc">$</span>coeff)</span></code></pre></div>
<pre><code>##           (Intercept) ravensData$ravenScore 
##             0.1863724             1.1124694</code></pre>
<div class="sourceCode" id="cb238"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb238-1"><a href="week-04.html#cb238-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">confint</span>(logRegRavens))</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                             2.5 %   97.5 %
## (Intercept)           0.005674966 3.106384
## ravensData$ravenScore 0.996229662 1.303304</code></pre>
<p>The resulting interval, ranging from 0.99 to 1.3, suggests that despite the established influence of scoring points on the Ravens’ game outcomes, this coefficient is not statistically significant.</p>
<p>The ANOVA function operates similarly to <code>lm</code>, taking the output of the fitted model and accommodating multiple models, including nested ones. It performs sequential tests, and in this case, a one Degree of Freedom test is conducted for the score variable, although its utility is limited in this specific example. ANOVA becomes more valuable when assessing several models or dealing with factor variables. It helps determine if a factor variable should be included or excluded, considering all levels collectively, in contrast to the independent testing of each level when using the summary function.</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="week-04.html#cb241-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(logRegRavens,<span class="at">test=</span><span class="st">&quot;Chisq&quot;</span>)</span></code></pre></div>
<pre><code>## Analysis of Deviance Table
## 
## Model: binomial, link: logit
## 
## Response: ravensData$ravenWinNum
## 
## Terms added sequentially (first to last)
## 
## 
##                       Df Deviance Resid. Df Resid. Dev Pr(&gt;Chi)  
## NULL                                     19     24.435           
## ravensData$ravenScore  1   3.5398        18     20.895  0.05991 .
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>When interpreting odds ratios, it’s crucial to note that they represent functions of probabilities, not probabilities themselves. An odds ratio of one indicates no difference, while on the Logit scale, a log odds ratio of zero implies no difference. Understanding these nuances is essential in the interpretation of logistic regression coefficients. An odds ratio below 0.5 or above 2 is often considered indicative of a strong effect. However, the significance of these values depends heavily on the context. In fields like epidemiology, where studies often involve noisy factors like nutrition and its impact on health, even a small odds ratio such as 1.01 might be significant in large-scale studies. On the other hand, in tightly controlled experimental clinical trials, larger odds ratios may be required to deem an effect meaningful. While the benchmarks of less than 0.5 or greater than 2 provide some guidance, their utility is limited and varies based on the scientific context.</p>
<p>The relative risk is another metric similar to the odds ratio and is favored by those who think more intuitively in terms of probabilities <span class="math inline">\(\frac{\rm{Pr}(RW_i | RS_i = 10)}{\rm{Pr}(RW_i | RS_i = 0)}\)</span>. It represents the ratio of two probabilities. Unlike odds ratios, relative risk introduces some model constraints, making relative risk regression less common for binary variables. In cases with small probabilities, the relative risk can approximate odds ratios, leading some to fit odds ratios but interpret them as if they were relative risks.</p>
</div>
<div id="poisson-regression" class="section level2" number="4.3">
<h2><span class="header-section-number">4.3</span> Poisson Regression</h2>
<div id="data-count" class="section level3" number="4.3.1">
<h3><span class="header-section-number">4.3.1</span> Data count</h3>
<p>Many data take the form of unbounded count data. For example, consider the number of calls to a call center or the number of flu cases in an area or the number of hits to a web site.</p>
<p>In some cases the counts are clearly bounded. However, modeling the counts as unbounded is often done when the upper limit is not known or very large relative to the number of events.</p>
<p>If the upper bound is known, the techniques we are discussing can be used to model the proportion or rate. The starting point for most count analysis is the the Poisson distribution.</p>
<p>In the following chapter, we go over some of the basics of modeling count data.</p>
</div>
<div id="poisson-regression-1" class="section level3" number="4.3.2">
<h3><span class="header-section-number">4.3.2</span> Poisson Regression</h3>
<p>This section focuses on Poisson Generalized Linear Models (GLMs), and credit is attributed to Jeff Leek for contributing much of the content from a previous version of the class. Count data modeling is a common need in various applications, such as the number of calls to a call center or the occurrences of flu cases. Count data can also be expressed as rates or proportions, like the percentage of people passing a test or the rate of cases over a specific time period, as seen in bio-statistics and public health, for instance, with incidence rates. Count, rates, and proportions all fall under the purview of Poisson GLMs. The Poisson distribution serves as a suitable model for count and rate data, where rates are counts per monitoring time. It is frequently used in modeling incidence rates, web traffic, and other scenarios. The Poisson distribution is also applied to approximate binomial probabilities when the success probability is very small, and the sample size is large. Contingency table data, involving counts of occurrences for different variables, is another area where Poisson models excel. A contingency table, illustrating counts of occurrences for various combinations of variables, finds an elegant framework in Poisson models. The Poisson mass function, presented in the lecture, defines the rate of counts per unit time as lambda, with t representing the total time. This distribution proves versatile for handling a variety of count data scenarios and provides a robust framework for statistical modeling.</p>
<p>The Poisson mass function <span class="math inline">\(X \sim Poisson(t\lambda)\)</span> is defined as:
<span class="math inline">\(P(X = x) = \frac{(t\lambda)^x e^{-t\lambda}}{x!}\)</span>
For <span class="math inline">\(x = 0, 1, \ldots\)</span>.</p>
<p>If x represents a positive value with a particular significance, its expected value equals <span class="math inline">\(t\lambda\)</span>. Consequently, our natural estimate of the rate is the count divided by the total time, denoted as <span class="math inline">\(\frac{x}{t}\)</span>. It’s noteworthy that in this scenario, the <span class="math inline">\(E[\)</span><span class="math inline">\(]\)</span>, our rate estimate, precisely equals lambda—the desired rate of estimation. The assumption underlying our model is that the variance equals the mean, which is <span class="math inline">\(t \lambda\)</span>. We can verify this assumption and explore potential solutions if it doesn’t hold. An interesting observation is that the Poisson distribution approaches a normal distribution as the mean increases. This can happen if <span class="math inline">\(t\)</span> is fixed and <span class="math inline">\(\lambda\)</span> increases, if <span class="math inline">\(\lambda\)</span> is fixed and <span class="math inline">\(t\)</span> increases, or if both <span class="math inline">\(t\)</span> and <span class="math inline">\(\lambda\)</span> increase. In various applications, the means may increase differently, but as long as they increase significantly, the Poisson distribution approximates a normal distribution. We illustrate this through simulations, presenting three sets of Poisson random variables as the mean of the distribution grows larger.</p>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="week-04.html#cb243-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>))</span>
<span id="cb243-2"><a href="week-04.html#cb243-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span> <span class="sc">:</span> <span class="dv">10</span>, <span class="fu">dpois</span>(<span class="dv">0</span> <span class="sc">:</span> <span class="dv">10</span>, <span class="at">lambda =</span> <span class="dv">2</span>), <span class="at">type =</span> <span class="st">&quot;h&quot;</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>)</span>
<span id="cb243-3"><a href="week-04.html#cb243-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span> <span class="sc">:</span> <span class="dv">20</span>, <span class="fu">dpois</span>(<span class="dv">0</span> <span class="sc">:</span> <span class="dv">20</span>, <span class="at">lambda =</span> <span class="dv">10</span>), <span class="at">type =</span> <span class="st">&quot;h&quot;</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>)</span>
<span id="cb243-4"><a href="week-04.html#cb243-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="dv">0</span> <span class="sc">:</span> <span class="dv">200</span>, <span class="fu">dpois</span>(<span class="dv">0</span> <span class="sc">:</span> <span class="dv">200</span>, <span class="at">lambda =</span> <span class="dv">100</span>), <span class="at">type =</span> <span class="st">&quot;h&quot;</span>, <span class="at">frame =</span> <span class="cn">FALSE</span>) </span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>The rightmost panel demonstrates the close resemblance to a normal distribution. Additionally, we can theoretically demonstrate that the mean and variance are equal. While this might not be suitable for this class, I encourage experimenting with simulations or exploring mathematical biostatistics courses, such as Brian Caffo’s other courses, for a detailed understanding of the mathematics behind this concept.</p>
<p>As an example, let’s analyze Jeff Leek’s web traffic on his <a href="www.biostat.jhsph.edu/~jleek">website</a>. The variable of interest in this case is the number of web hits per day, with the unit of time set as <span class="math inline">\(t\)</span> equals one day. To interpret the data as web hits per hour, <span class="math inline">\(t\)</span> would need to be set to 24. Similarly, for seconds, it would be <span class="math inline">\(t=24\times 60\)</span>, and so on.</p>
<div class="sourceCode" id="cb244"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb244-1"><a href="week-04.html#cb244-1" aria-hidden="true" tabindex="-1"></a><span class="fu">download.file</span>(<span class="st">&quot;https://raw.githubusercontent.com/B7M/Course_data/main/gaData.csv&quot;</span>,<span class="at">destfile=</span><span class="st">&quot;gaData.csv&quot;</span>,<span class="at">method=</span><span class="st">&quot;auto&quot;</span>)</span>
<span id="cb244-2"><a href="week-04.html#cb244-2" aria-hidden="true" tabindex="-1"></a>gaData <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;gaData.csv&quot;</span>)</span>
<span id="cb244-3"><a href="week-04.html#cb244-3" aria-hidden="true" tabindex="-1"></a>gaData<span class="sc">$</span>date <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(gaData<span class="sc">$</span>date)</span>
<span id="cb244-4"><a href="week-04.html#cb244-4" aria-hidden="true" tabindex="-1"></a>gaData<span class="sc">$</span>julian <span class="ot">&lt;-</span> <span class="fu">julian</span>(gaData<span class="sc">$</span>date)</span>
<span id="cb244-5"><a href="week-04.html#cb244-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(gaData)</span></code></pre></div>
<pre><code>##         date visits simplystats julian
## 1 2011-01-01      0           0  14975
## 2 2011-01-02      0           0  14976
## 3 2011-01-03      0           0  14977
## 4 2011-01-04      0           0  14978
## 5 2011-01-05      0           0  14979
## 6 2011-01-06      0           0  14980</code></pre>
<p>After downloading the data, the date is converted from a standard character date-time format to a Julian date, counting the days since January 1st, 1970. The dataset includes the date, number of visits, and Julian date. Early dates show zero visits. A plot of the dataset illustrates the relationship between Julian date and the number of visits.</p>
<div class="sourceCode" id="cb246"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb246-1"><a href="week-04.html#cb246-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gaData<span class="sc">$</span>julian,gaData<span class="sc">$</span>visits,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span><span class="st">&quot;darkgrey&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Julian&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Visits&quot;</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>Considering linear regression for modeling count data, as discussed in the last lecture, there are challenges. However, with larger mean counts, concerns decrease due to the tendency of counts towards a normal distribution. Here we will define the following model: <span class="math display">\[ NH_i = b_0 + b_1 JD_i + e_i \]</span></p>
<p><span class="math inline">\(NH_i\)</span> - number of hits to the website</p>
<p><span class="math inline">\(JD_i\)</span> - day of the year (Julian day)</p>
<p><span class="math inline">\(b_0\)</span> - number of hits on Julian day 0 (1970-01-01)</p>
<p><span class="math inline">\(b_1\)</span> - increase in number of hits per unit day</p>
<p><span class="math inline">\(e_i\)</span> - variation due to everything we didn’t measure</p>
<p>And fit a linear regression model.</p>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="week-04.html#cb247-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gaData<span class="sc">$</span>julian,gaData<span class="sc">$</span>visits,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span><span class="st">&quot;darkgrey&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Julian&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Visits&quot;</span>)</span>
<span id="cb247-2"><a href="week-04.html#cb247-2" aria-hidden="true" tabindex="-1"></a>lm1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(gaData<span class="sc">$</span>visits <span class="sc">~</span> gaData<span class="sc">$</span>julian)</span>
<span id="cb247-3"><a href="week-04.html#cb247-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(lm1,<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>The fitted line shows some curvature, suggesting potential issues. While this initial approach may not be ideal for small counts, it serves as a starting point. Linear models may lack optimal interpretation for count data, prompting exploration of ways to improve interpretation in subsequent slides. Viewing counts as relative scales, rather than linear additive scales, is considered for a more meaningful interpretation of linear models. To this end we take the natural logarithm of the outcome variable. The model is expressed as <span class="math display">\[log(NH_i) = b_0 + b_1(JD_i) + e_i\]</span>
where <span class="math inline">\(b_0, b_1\)</span> are coefficients, <span class="math inline">\(JD_i\)</span> is the Julian date, and <span class="math inline">\(e_i\)</span> represents the error term. The logarithm has a meaningful interpretation in terms of geometric means. The exponential value of the logarithm’s expected value for a random variable is what we refer to as the population geometric mean, <span class="math inline">\(e^{E[\log(Y)]}\)</span>. This term is derived from the empirical or geometric mean, which is the product of a sample represented as <span class="math inline">\(e^{\frac{1}{n}\sum_{i=1}^n \log(y_i)} = (\prod_{i=1}^n y_i)^{1/n}\)</span>. To clarify, this is equivalent to the product of <span class="math inline">\(Y_i\)</span> to the power of one over n. Taking the logarithm of this yields the arithmetic mean or the average of the log data. In essence, the geometric mean is obtained by exponentiating the arithmetic mean of the log data. As we gather more data in our sample, the arithmetic mean tends to converge to a certain value, and the geometric mean represents what this quantity, the product of the data raised to the power of <span class="math inline">\(\frac{1}{n}\)</span>, converges to. When we apply the natural logarithm to the outcome in a linear regression, the exponentiated coefficients become interpretable in terms of geometric means. For instance, <span class="math inline">\(e^{\beta_0}\)</span> signifies the estimated geometric mean hits on day zero.</p>
<div class="sourceCode" id="cb248"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb248-1"><a href="week-04.html#cb248-1" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(<span class="fu">exp</span>(<span class="fu">coef</span>(<span class="fu">lm</span>(<span class="fu">I</span>(<span class="fu">log</span>(gaData<span class="sc">$</span>visits <span class="sc">+</span> <span class="dv">1</span>)) <span class="sc">~</span> gaData<span class="sc">$</span>julian))), <span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   (Intercept) gaData$julian 
##       0.00000       1.00231</code></pre>
<p>It’s important to note, as emphasized earlier, that the intercept (<span class="math inline">\(\beta_0\)</span>) might not carry significant meaning since January 1, 1970, is not a relevant date in terms of web hits. To enhance interpretability, a better approach would have been to subtract the earliest date observed in the dataset and begin counting days from there. Consequently, the intercept would then represent the exponentiated value of the estimated intercept as the geometric mean hits on the first day of the dataset. The adjustment in the intercept is a minor modification that doesn’t alter the fitted model’s slope or other aspects. Nevertheless, for those seeking an interpretable intercept such adjustments become relevant.
<span class="math inline">\(e^{\beta_1}\)</span> on the other hand, represents the estimated proportional increase or decrease in the geometric mean hits per day. It’s crucial to address an issue with logarithms when dealing with zero counts. Taking the logarithm of zero is undefined, so a common solution is to add a constant, often plus one, to the counts. Thus, we perform the log of the outcome plus one. In a linear model fitted to the log of the outcome plus one against the Julian date, the intercept, as mentioned earlier, may not carry significant meaning. However, the coefficient of 1.002, when exponentiated, indicates a 0.2% daily increase in web traffic according to our model. This interpretation holds if no additional covariates are considered. Introducing other covariates would lead to a 0.02% daily increase, keeping the other covariates constant.</p>
</div>
<div id="linear-vs.-poisson-regression" class="section level3" number="4.3.3">
<h3><span class="header-section-number">4.3.3</span> Linear vs. Poisson regression</h3>
<p><strong>Linear</strong></p>
<p>$ NH_i = b_0 + b_1 JD_i + e_i $
or
$ E[NH_i | JD_i, b_0, b_1] = b_0 + b_1 JD_i$</p>
<p><strong>Poisson/log-linear</strong></p>
<p>$ (E[NH_i | JD_i, b_0, b_1]) = b_0 + b_1 JD_i $
or
$ E[NH_i | JD_i, b_0, b_1] = (b_0 + b_1 JD_i) $</p>
<p>In Generalized Linear Models (GLMs), the focus isn’t directly on the outcome or its transformation; instead, we concentrate on the transformation of the mean of the outcome. In linear models, the outcome is represented as the linear component plus an error, or equivalently, the expected value of the outcome is the linear component. On the other hand, in a Poisson/ log-linear model, the linear part is the log of the expected outcome. For example, the log of the expected number of web hits per day is expressed as <span class="math inline">\(b_0 + b_1 JD_i\)</span>. By exponentiating both sides of this equation, we can state that the mean web hits per day depend on <span class="math inline">\(e^{\text{linear regression model}}\)</span>. The key distinction lies in assuming that our data follows a Poisson distribution with a mean defined as <span class="math inline">\(e^{b0 + b1 \times regressor}\)</span>. This alteration significantly affects the interpretation of the model, providing a more plausible distribution for observed outcomes. Moreover, since everything is logged, the coefficients are interpreted in a relative sense, similar to when we logged the outcome. This approach mitigates issues encountered in the previous example, such as taking logs of 0.
It’s worth emphasizing the utility of taking logs of outcomes, which is a valuable technique for count data and also for general regression. When dealing with positive data, the logarithmic transformation is often one of the most beneficial. It maintains or even enhances the interpretability of coefficients on the log scale. However, when considering other transformations such as square root or cube root, the complexities arise. It’s crucial to remember that the differences observed in transformed data are multiplicative when returning to the natural scale.</p>
<p>Examining the model where the expected value of the outcome is <span class="math inline">\(e^{\beta_0 + \beta_1 JD}\)</span>, by leveraging the properties of expected value, we can factor out <span class="math inline">\(e^{\beta_0}, e^{\beta_1 JD}\)</span>.</p>
<p><span class="math inline">\(E[NH_i | JD_i, b_0, b_1] = \exp\left(b_0 + b_1 JD_i\right)\)</span>
$ E[NH_i | JD_i, b_0, b_1] = (b_0 )(b_1 JD_i) $</p>
<p>If we explore the expected mean for the next day (Julian date plus one), represented as <span class="math inline">\(e^{b0 + b1 (JD + 1)}\)</span>, dividing this by the current expected mean yields <span class="math inline">\(e^{b_1}\)</span>. Consequently, the coefficient <span class="math inline">\(e^{\text{the slope coefficient}}\)</span> is interpreted as the relative increase or decrease in the mean for a one-unit change in the regressor. Exponentiating the coefficients allows us to assess whether they are close to 1, while leaving them on the log scale enables an evaluation of their proximity to 0. In the multivariate setting, <span class="math inline">\(e^{\beta_1}\)</span> signifies the expected relative increase or decrease in web traffic, holding the other coefficients constant.</p>
<p>Moving on to the fitted Poisson regression model overlaid onto the data, it closely aligns with the linear model but exhibits desired curvature.</p>
<div class="sourceCode" id="cb250"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb250-1"><a href="week-04.html#cb250-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(gaData<span class="sc">$</span>julian,gaData<span class="sc">$</span>visits,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span><span class="st">&quot;darkgrey&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Julian&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Visits&quot;</span>)</span>
<span id="cb250-2"><a href="week-04.html#cb250-2" aria-hidden="true" tabindex="-1"></a>glm1 <span class="ot">&lt;-</span> <span class="fu">glm</span>(gaData<span class="sc">$</span>visits <span class="sc">~</span> gaData<span class="sc">$</span>julian,<span class="at">family=</span><span class="st">&quot;poisson&quot;</span>)</span>
<span id="cb250-3"><a href="week-04.html#cb250-3" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(lm1,<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">lwd=</span><span class="dv">3</span>); <span class="fu">lines</span>(gaData<span class="sc">$</span>julian,glm1<span class="sc">$</span>fitted,<span class="at">col=</span><span class="st">&quot;blue&quot;</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>This curvature could have been achieved in the linear model by introducing a squared term, yet it’s noteworthy that a simpler model with fewer coefficients seems to offer a better fit. One common concern is the requirement for variance to equal the mean. However, when examining the plot of fitted values versus residuals, it becomes apparent that the variance is higher for lower mean values, indicating a potential issue.</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="week-04.html#cb251-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(glm1<span class="sc">$</span>fitted,glm1<span class="sc">$</span>residuals,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Residuals&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Fitted&quot;</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Thus, there’s a need for a mechanism to address the non-constant variance. Addressing the non-constant variance in models like the Poisson regression can be approached through various methods. One approach discussed in the book is the quasi-Poisson model, which allows for the variance to be a constant multiple of the mean rather than strictly equal to it. However, in cases like the one presented, where there’s larger variance for lower fitted values, indicating a violation of the Poisson model assumption, alternative solutions are necessary.</p>
<p>Jeff shared code for a model-agnostic standard errors approach using the sandwich package.</p>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="week-04.html#cb252-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sandwich)</span></code></pre></div>
<pre><code>## Warning: package &#39;sandwich&#39; was built under R version 4.0.3</code></pre>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="week-04.html#cb254-1" aria-hidden="true" tabindex="-1"></a>confint.agnostic <span class="ot">&lt;-</span> <span class="cf">function</span> (object, parm, <span class="at">level =</span> <span class="fl">0.95</span>, ...)</span>
<span id="cb254-2"><a href="week-04.html#cb254-2" aria-hidden="true" tabindex="-1"></a>{</span>
<span id="cb254-3"><a href="week-04.html#cb254-3" aria-hidden="true" tabindex="-1"></a>    cf <span class="ot">&lt;-</span> <span class="fu">coef</span>(object); pnames <span class="ot">&lt;-</span> <span class="fu">names</span>(cf)</span>
<span id="cb254-4"><a href="week-04.html#cb254-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">missing</span>(parm))</span>
<span id="cb254-5"><a href="week-04.html#cb254-5" aria-hidden="true" tabindex="-1"></a>        parm <span class="ot">&lt;-</span> pnames</span>
<span id="cb254-6"><a href="week-04.html#cb254-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span> <span class="cf">if</span> (<span class="fu">is.numeric</span>(parm))</span>
<span id="cb254-7"><a href="week-04.html#cb254-7" aria-hidden="true" tabindex="-1"></a>        parm <span class="ot">&lt;-</span> pnames[parm]</span>
<span id="cb254-8"><a href="week-04.html#cb254-8" aria-hidden="true" tabindex="-1"></a>    a <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">-</span> level)<span class="sc">/</span><span class="dv">2</span>; a <span class="ot">&lt;-</span> <span class="fu">c</span>(a, <span class="dv">1</span> <span class="sc">-</span> a)</span>
<span id="cb254-9"><a href="week-04.html#cb254-9" aria-hidden="true" tabindex="-1"></a>    pct <span class="ot">&lt;-</span> stats<span class="sc">:::</span><span class="fu">format.perc</span>(a, <span class="dv">3</span>)</span>
<span id="cb254-10"><a href="week-04.html#cb254-10" aria-hidden="true" tabindex="-1"></a>    fac <span class="ot">&lt;-</span> <span class="fu">qnorm</span>(a)</span>
<span id="cb254-11"><a href="week-04.html#cb254-11" aria-hidden="true" tabindex="-1"></a>    ci <span class="ot">&lt;-</span> <span class="fu">array</span>(<span class="cn">NA</span>, <span class="at">dim =</span> <span class="fu">c</span>(<span class="fu">length</span>(parm), 2L), <span class="at">dimnames =</span> <span class="fu">list</span>(parm,</span>
<span id="cb254-12"><a href="week-04.html#cb254-12" aria-hidden="true" tabindex="-1"></a>                                                               pct))</span>
<span id="cb254-13"><a href="week-04.html#cb254-13" aria-hidden="true" tabindex="-1"></a>    ses <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">diag</span>(sandwich<span class="sc">::</span><span class="fu">vcovHC</span>(object)))[parm]</span>
<span id="cb254-14"><a href="week-04.html#cb254-14" aria-hidden="true" tabindex="-1"></a>    ci[] <span class="ot">&lt;-</span> cf[parm] <span class="sc">+</span> ses <span class="sc">%o%</span> fac</span>
<span id="cb254-15"><a href="week-04.html#cb254-15" aria-hidden="true" tabindex="-1"></a>    ci</span>
<span id="cb254-16"><a href="week-04.html#cb254-16" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div>
<p>The sandwich variance estimator, famous for generalized estimating equations, originated at Johns Hopkins Biostatistics. This technique, although a bit advanced, is crucial in practice. It involves conducting residual plots to assess model assumptions. If the quasi-Poisson model is deemed suitable, especially when assumptions about variance being a constant multiple of the mean are not strictly met, it can be easily implemented in R.</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="week-04.html#cb255-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(glm1)</span></code></pre></div>
<pre><code>## Waiting for profiling to be done...</code></pre>
<pre><code>##                       2.5 %        97.5 %
## (Intercept)   -34.346577587 -31.159715656
## gaData$julian   0.002190043   0.002396461</code></pre>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="week-04.html#cb258-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint.agnostic</span>(glm1)</span></code></pre></div>
<pre><code>##                       2.5 %        97.5 %
## (Intercept)   -36.362674594 -29.136997254
## gaData$julian   0.002058147   0.002527955</code></pre>
<p>For cases where model assumptions are significantly violated, more advanced solutions may be required. In the example presented, confidence intervals are shown without any adjustment and with the model-agnostic approach. While there’s not a substantial difference in this particular case, it’s essential to explore these options when necessary. Both confidence intervals presented are in their non-exponentiated form. This advanced topic underscores the importance of thoroughly examining model assumptions and employing appropriate techniques to address issues arising in practical applications. Exponentiating coefficients, especially for small ones, essentially adds 1. For instance, if the coefficient is around 0.002, exponentiating it might be approximately 1.002. Continuing with the example, this translates to about a 0.2% increase on the lower end, and a 0.3% increase per day on the high end.</p>
</div>
<div id="how-should-we-handle-rates-and-proportions" class="section level3" number="4.3.4">
<h3><span class="header-section-number">4.3.4</span> How should we handle rates and proportions?</h3>
<p>When dealing with rates and proportions, it’s essential to distinguish between the two. Rates involve counts with an associated offset that helps interpret the count relative to some factor, such as time, population size, or sample size.
$ E[NHSS_i | JD_i, b_0, b_1]/NH_i = (b_0 + b_1 JD_i) $</p>
<p>In the example of web hits, Jeff is interested in the number of web hits from Simply Statistic relative to the total number of web hits, modeling this proportion as <span class="math inline">\(e^{b_0 + b_1 JD_i}\)</span>. To achieve this in R, the key is to interpret the expected value of the outcome divided by the relative term.
<span class="math display">\[ \log\left(E[NHSS_i | JD_i, b_0, b_1]\right) - \log(NH_i)  =  b_0 + b_1 JD_i \]</span>
<span class="math display">\[ \log\left(E[NHSS_i | JD_i, b_0, b_1]\right) = \log(NH_i) + b_0 + b_1 JD_i \]</span></p>
<p>By taking the log of both sides and manipulating the equation, a similar log-linear model is obtained, featuring the log of the outcome as the linear regression part and a log offset without a coefficient. This simple addition of a log offset with no coefficient is all that is required to incorporate a regular proportion into a Poisson Generalized Linear Model (GLM).</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="week-04.html#cb260-1" aria-hidden="true" tabindex="-1"></a>glm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(gaData<span class="sc">$</span>simplystats <span class="sc">~</span> <span class="fu">julian</span>(gaData<span class="sc">$</span>date),<span class="at">offset=</span><span class="fu">log</span>(visits<span class="sc">+</span><span class="dv">1</span>),</span>
<span id="cb260-2"><a href="week-04.html#cb260-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">family=</span><span class="st">&quot;poisson&quot;</span>,<span class="at">data=</span>gaData)</span>
<span id="cb260-3"><a href="week-04.html#cb260-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">julian</span>(gaData<span class="sc">$</span>date),glm2<span class="sc">$</span>fitted,<span class="at">col=</span><span class="st">&quot;blue&quot;</span>,<span class="at">pch=</span><span class="dv">19</span>,<span class="at">xlab=</span><span class="st">&quot;Date&quot;</span>,<span class="at">ylab=</span><span class="st">&quot;Fitted Counts&quot;</span>)</span>
<span id="cb260-4"><a href="week-04.html#cb260-4" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="fu">julian</span>(gaData<span class="sc">$</span>date),glm1<span class="sc">$</span>fitted,<span class="at">col=</span><span class="st">&quot;red&quot;</span>,<span class="at">pch=</span><span class="dv">19</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>To incorporate the relative denominator count or time into the linear model for rates and proportions, you can easily add it as a log offset. An effective way to do this is by using the term <code>offset = log(visits + 1)</code> in the GLM function. The <code>+1</code> is added to avoid issues with taking the log of 0. Ensure to specify <code>family = Poisson</code> in the model statement, which assumes a log link by default.</p>
<p>Jeff compares two fitted rates using GLM1 and GLM2. GLM1 is based on the number of web hits, while GLM2 is based on the relative number of web hits originating from Simply Statistics. The blue points, adjusted for the red points, represent the fitted model relative to the data, showing a temporal component with numerous zeros early on. For handling zero inflation in Poisson data, various approaches exist, and it’s crucial to consider the specific characteristics of the dataset. Jeff used a package that aids in modeling zero inflation, addressing concerns about an excessive number of zeros.</p>
<p>In the following example the graph presented depicts the fitted model in relation to the data, showcasing a surge in values after an initial period of numerous zeros. The blue line represents the fitted model, while the gray points correspond to the actual data points.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="week-04.html#cb261-1" aria-hidden="true" tabindex="-1"></a>glm2 <span class="ot">&lt;-</span> <span class="fu">glm</span>(gaData<span class="sc">$</span>simplystats <span class="sc">~</span> <span class="fu">julian</span>(gaData<span class="sc">$</span>date),<span class="at">offset=</span><span class="fu">log</span>(visits<span class="sc">+</span><span class="dv">1</span>),</span>
<span id="cb261-2"><a href="week-04.html#cb261-2" aria-hidden="true" tabindex="-1"></a>            <span class="at">family=</span><span class="st">&quot;poisson&quot;</span>,<span class="at">data=</span>gaData)</span>
<span id="cb261-3"><a href="week-04.html#cb261-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">julian</span>(gaData<span class="sc">$</span>date),gaData<span class="sc">$</span>simplystats<span class="sc">/</span>(gaData<span class="sc">$</span>visits<span class="sc">+</span><span class="dv">1</span>),<span class="at">col=</span><span class="st">&quot;grey&quot;</span>,<span class="at">xlab=</span><span class="st">&quot;Date&quot;</span>,</span>
<span id="cb261-4"><a href="week-04.html#cb261-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="st">&quot;Fitted Rates&quot;</span>,<span class="at">pch=</span><span class="dv">19</span>)</span>
<span id="cb261-5"><a href="week-04.html#cb261-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">julian</span>(gaData<span class="sc">$</span>date),glm2<span class="sc">$</span>fitted<span class="sc">/</span>(gaData<span class="sc">$</span>visits<span class="sc">+</span><span class="dv">1</span>),<span class="at">col=</span><span class="st">&quot;blue&quot;</span>,<span class="at">lwd=</span><span class="dv">3</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-18-1.png" width="672" /></p>
</div>
<div id="more-information" class="section level3" number="4.3.5">
<h3><span class="header-section-number">4.3.5</span> More information</h3>
<ul>
<li><a href="http://ww2.coastal.edu/kingw/statistics/R-tutorials/loglin.html">Log-linear models and multiway tables</a></li>
<li><a href="http://en.wikipedia.org/wiki/Poisson_regression">Wikipedia on Poisson regression</a>, <a href="http://en.wikipedia.org/wiki/Overdispersion">Wikipedia on overdispersion</a></li>
<li><a href="http://cran.r-project.org/web/packages/pscl/vignettes/countreg.pdf">Regression models for count data in R</a></li>
<li><a href="http://cran.r-project.org/web/packages/pscl/index.html">pscl package</a> - the function <em>zeroinfl</em> fits zero inflated models.</li>
</ul>
</div>
</div>
<div id="hodgepodge" class="section level2" number="4.4">
<h2><span class="header-section-number">4.4</span> Hodgepodge</h2>
<p>This section is a bit of mishmash of interesting things that one can accomplish with linear models.</p>
<p>In this final section, we aim to inspire you to continue exploring regression models and linear models, emphasizing their immense importance in data analysis. We will share a couple of interesting insights that extend the capabilities of linear models beyond what we’ve covered so far.</p>
<p>When thinking about extending linear models, the first consideration is fitting complex functions using regression models. While we’ve explored adding squared and cubic terms to capture lower-order functions, what if the function is more intricate, like a sine curve? How can we fit such non-parametric functions using a linear model? One approach is to specify our model as <span class="math inline">\(Y = f(x) + ε\)</span>, where <span class="math inline">\(f\)</span> represents a potentially complicated function. Surprisingly, there’s a relatively straightforward way to achieve this, and we will introduce you to a simple initial step. Keep in mind that there’s an entire literature on this topic, and we’ll cover some fundamental concepts.</p>
<p>The first step involves using something called regression splines. The model for <span class="math inline">\(Y = f(X) + ε\)</span> includes an intercept (<span class="math inline">\(β₀\)</span>), a regular slope term (<span class="math inline">\(β₁ X₁\)</span>), and additional terms involving the sum of terms of the form <span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + \sum_{k=1}^d (x_i - \xi_k)_+ \gamma_k + \epsilon_{i}\]</span></p>
<p>where <span class="math inline">\((a)_+ = a\)</span> if <span class="math inline">\(a &gt; 0\)</span> and <span class="math inline">\(0\)</span> otherwise and <span class="math inline">\(\xi_i\)</span> are known knot points.</p>
<p>The idea behind regression splines involves creating kinks or breaks in a stick rather than breaking it apart. Imagine having a stick, and instead of breaking it, you introduce kinks at specific points. Now, if you aim to fit a function to your data, and the data exhibits a pattern like zigzag, you might want to create breaks at certain points to capture the complexity of the function. Mathematically modeling these breaks is precisely what the little plus functions do in the context of regression splines. The process involves introducing these “kinks” at selected points in the data to better represent the underlying function. It’s worth noting that these functions help ensure continuity in the overall model. If you’re interested, you can delve deeper into the mathematical aspects and prove to yourself that the resulting function remains continuous despite the introduced breaks. This continuity is a crucial aspect of the approach, allowing for a more flexible and accurate representation of complex functions in the data. The easiest way to show this would be to go through an example.</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="week-04.html#cb262-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">500</span>; x <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">4</span> <span class="sc">*</span> pi, <span class="at">length =</span> n); y <span class="ot">&lt;-</span> <span class="fu">sin</span>(x) <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="at">sd =</span> .<span class="dv">3</span>)</span>
<span id="cb262-2"><a href="week-04.html#cb262-2" aria-hidden="true" tabindex="-1"></a>knots <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">8</span> <span class="sc">*</span> pi, <span class="at">length =</span> <span class="dv">20</span>); </span>
<span id="cb262-3"><a href="week-04.html#cb262-3" aria-hidden="true" tabindex="-1"></a>splineTerms <span class="ot">&lt;-</span> <span class="fu">sapply</span>(knots, <span class="cf">function</span>(knot) (x <span class="sc">&gt;</span> knot) <span class="sc">*</span> (x <span class="sc">-</span> knot))</span>
<span id="cb262-4"><a href="week-04.html#cb262-4" aria-hidden="true" tabindex="-1"></a>xMat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="dv">1</span>, x, splineTerms)</span>
<span id="cb262-5"><a href="week-04.html#cb262-5" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="fu">lm</span>(y <span class="sc">~</span> xMat <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb262-6"><a href="week-04.html#cb262-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">frame =</span> <span class="cn">FALSE</span>, <span class="at">pch =</span> <span class="dv">21</span>, <span class="at">bg =</span> <span class="st">&quot;lightblue&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb262-7"><a href="week-04.html#cb262-7" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x, yhat, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>In this example, simulated data is generated, representing a sine curve with added noise, as seen in the blue points on the plot. The goal is to fit a model to this data using regression splines. To achieve this, a set of knots (breakpoints where the line will be continuous but not smooth) is calculated. In this case, 20 knots are evenly spaced along the range of the collected data. The creation of the matrix of knot terms is illustrated, showcasing how to implement the function discussed earlier. This matrix serves as a basis for constructing the x matrix, which includes an intercept term, a slope coefficient term (x by itself), and the spline terms. The model is then fitted using these predictors, with the intercept excluded from the model since it’s already incorporated in the x matrix. The resulting fitted plot looks promising, effectively capturing the sine curve. However, one notable aspect is that the fit appears sharp at the knots. Mathematically, this occurs because although the function used is continuous, it lacks continuity in its derivatives, making it not continuously differentiable. This characteristic may lead to sharp transitions at the knot points, which can be a consideration when applying regression splines to capture smooth functions.</p>
<p>To address the issue of a non-continuous derivative at the knot points and achieve a smoother curve, a simple trick involves adding square terms. Instead of having a function with x minus the knot points, marked with a little plus symbol, you square that difference.
<span class="math display">\[Y_i = \beta_0 + \beta_1 X_i + \beta_2 X_i^2 + \sum_{k=1}^d (x_i - \xi_k)_+^2 \gamma_k + \epsilon_{i}\]</span>
The updated function maintains the same structure as before but incorporating the square term.</p>
<p>Mathematically, the squared term ensures that if the x-coordinate is beyond the knot point, the difference is squared, creating a smooth transition. The function is defined as <span class="math inline">\((x_i-\xi_k)^2\)</span> if x is greater than the knot point, and zero otherwise.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="week-04.html#cb263-1" aria-hidden="true" tabindex="-1"></a>splineTerms <span class="ot">&lt;-</span> <span class="fu">sapply</span>(knots, <span class="cf">function</span>(knot) (x <span class="sc">&gt;</span> knot) <span class="sc">*</span> (x <span class="sc">-</span> knot)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb263-2"><a href="week-04.html#cb263-2" aria-hidden="true" tabindex="-1"></a>xMat <span class="ot">&lt;-</span> <span class="fu">cbind</span>(<span class="dv">1</span>, x, x<span class="sc">^</span><span class="dv">2</span>, splineTerms)</span>
<span id="cb263-3"><a href="week-04.html#cb263-3" aria-hidden="true" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="fu">lm</span>(y <span class="sc">~</span> xMat <span class="sc">-</span> <span class="dv">1</span>))</span>
<span id="cb263-4"><a href="week-04.html#cb263-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(x, y, <span class="at">frame =</span> <span class="cn">FALSE</span>, <span class="at">pch =</span> <span class="dv">21</span>, <span class="at">bg =</span> <span class="st">&quot;lightblue&quot;</span>, <span class="at">cex =</span> <span class="dv">2</span>)</span>
<span id="cb263-5"><a href="week-04.html#cb263-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(x, yhat, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>The code remains almost identical to the previous version, with the addition of squaring the difference for points beyond the knot. When fitting the model with this modification, the resulting curve appears smooth, effectively addressing the discontinuity issue at the knot points. It’s important to note that this process involves ordinary regression, showcasing the flexibility of regression models in capturing complex functions.</p>
<p>In this example, we’ve successfully fitted a complex function using ordinary regression by incorporating a set of knots. However, there are certain challenges associated with this basic version of regression splines. One key challenge is determining the precise locations of the knot points. Too many or too few knot points can introduce potential issues. To address these challenges, there are more advanced techniques and solutions. It’s essential to recognize that the collection of sine terms introduced earlier is termed a basis, representing building blocks for functions. While regression splines are one way to create a basis, there are various other approaches. Some popular bases include the Fourier basis (which will be discussed shortly), the wavelet basis, and spline bases like the regression splines we’ve explored. Different bases have distinct strengths and weaknesses, and researchers invest considerable effort in developing and understanding these foundations. If the goal is to fit data with a specific shape, such as a hockey stick, having just one knot point may be sufficient. This approach can capture abrupt changes in the data, like a hockey stick model, provided the location of the knot point is precisely known. It’s important to note that fitting non-linear functions is not limited to linear models; it can also be extended to generalized linear models (GLMs). The process involves specifying the regression in the linear predictor, allowing for the flexibility to handle non-linear relationships in a more generalized framework. One consistent challenge in this approach is the determination of knot points (naught points). Too few or too many knot points can pose problems. A modern solution to address this challenge involves incorporating many knot points and adding a regularization term. The regularization term penalizes coefficients from spline terms, discouraging excessively large coefficients and helping control the number of parameters in the model. While regularization is a more advanced topic, it is commonly covered in advanced linear modeling or regression modeling classes. By understanding the basics of fitting non-linear functions using linear and generalized linear models, you now have a foundation for further exploration. Experimenting with knot placement and the number of knots is a practical starting point. To delve deeper into this topic, consider taking additional classes in linear models to extend your knowledge and skills.</p>
<p>In the next example, the focus is on creating another basis known as the Fourier basis and exploring how to model harmonics using it. The exercise involves imagining a major scale, which consists of eight notes: do, re, mi, fa, so, la, ti, do. A chord, in this context, refers to three notes played together. The question posed is whether, given a continuous chord played for some time and digitized into R, the software would be able to figure out the notes comprising the chord based solely on the sound.</p>
<p>The data for this exercise was generated, and the frequencies for various notes were obtained from the Internet. The frequencies correspond to notes starting from the middle C key on a piano and going up one octave to the C key again. The goal is to take these notes and create digitally sampled time points for analysis. Now, let’s proceed with the analysis of this data to see if R can deduce the notes comprising the chord based on the digitized sound.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="week-04.html#cb264-1" aria-hidden="true" tabindex="-1"></a><span class="do">##Chord finder, playing the white keys on a piano from octave c4 - c5</span></span>
<span id="cb264-2"><a href="week-04.html#cb264-2" aria-hidden="true" tabindex="-1"></a>notes4 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">261.63</span>, <span class="fl">293.66</span>, <span class="fl">329.63</span>, <span class="fl">349.23</span>, <span class="fl">392.00</span>, <span class="fl">440.00</span>, <span class="fl">493.88</span>, <span class="fl">523.25</span>)</span>
<span id="cb264-3"><a href="week-04.html#cb264-3" aria-hidden="true" tabindex="-1"></a>t <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">2</span>, <span class="at">by =</span> .<span class="dv">001</span>); n <span class="ot">&lt;-</span> <span class="fu">length</span>(t)</span>
<span id="cb264-4"><a href="week-04.html#cb264-4" aria-hidden="true" tabindex="-1"></a>c4 <span class="ot">&lt;-</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> notes4[<span class="dv">1</span>] <span class="sc">*</span> t); e4 <span class="ot">&lt;-</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> notes4[<span class="dv">3</span>] <span class="sc">*</span> t); </span>
<span id="cb264-5"><a href="week-04.html#cb264-5" aria-hidden="true" tabindex="-1"></a>g4 <span class="ot">&lt;-</span> <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> notes4[<span class="dv">5</span>] <span class="sc">*</span> t)</span>
<span id="cb264-6"><a href="week-04.html#cb264-6" aria-hidden="true" tabindex="-1"></a>chord <span class="ot">&lt;-</span> c4 <span class="sc">+</span> e4 <span class="sc">+</span> g4 <span class="sc">+</span> <span class="fu">rnorm</span>(n, <span class="dv">0</span>, <span class="fl">0.3</span>)</span>
<span id="cb264-7"><a href="week-04.html#cb264-7" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">sapply</span>(notes4, <span class="cf">function</span>(freq) <span class="fu">sin</span>(<span class="dv">2</span> <span class="sc">*</span> pi <span class="sc">*</span> freq <span class="sc">*</span> t))</span>
<span id="cb264-8"><a href="week-04.html#cb264-8" aria-hidden="true" tabindex="-1"></a>fit <span class="ot">&lt;-</span> <span class="fu">lm</span>(chord <span class="sc">~</span> x <span class="sc">-</span> <span class="dv">1</span>)</span></code></pre></div>
<p>The chord is created using three notes: C, E, and G. Each note is generated by creating a sine wave at the corresponding frequency. While R lacks the capability to directly play these frequencies as sound, the resulting chord would sound like a digital representation of a C major chord if played. To analyze the chord, a basis is created using sine functions for every note (eight sine functions in total). A linear model is then fitted with the chord as the outcome and the sine functions as predictors. The intercept is removed since everything is centered to have mean zero. The coefficients obtained from this model are then plotted, revealing that R correctly estimates the coefficients for C, E, and G as being relatively large compared to the other notes.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="week-04.html#cb265-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">9</span>), <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">1.5</span>), <span class="at">xlab =</span> <span class="st">&quot;Note&quot;</span>, <span class="at">ylab =</span> <span class="st">&quot;Coef^2&quot;</span>, <span class="at">axes =</span> <span class="cn">FALSE</span>, <span class="at">frame =</span> <span class="cn">TRUE</span>, <span class="at">type =</span> <span class="st">&quot;n&quot;</span>)</span>
<span id="cb265-2"><a href="week-04.html#cb265-2" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">2</span>)</span>
<span id="cb265-3"><a href="week-04.html#cb265-3" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at =</span> <span class="dv">1</span> <span class="sc">:</span> <span class="dv">8</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;c4&quot;</span>, <span class="st">&quot;d4&quot;</span>, <span class="st">&quot;e4&quot;</span>, <span class="st">&quot;f4&quot;</span>, <span class="st">&quot;g4&quot;</span>, <span class="st">&quot;a4&quot;</span>, <span class="st">&quot;b4&quot;</span>, <span class="st">&quot;c5&quot;</span>))</span>
<span id="cb265-4"><a href="week-04.html#cb265-4" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span> <span class="sc">:</span> <span class="dv">8</span>) <span class="fu">abline</span>(<span class="at">v =</span> i, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="fu">grey</span>(.<span class="dv">8</span>))</span>
<span id="cb265-5"><a href="week-04.html#cb265-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span> <span class="sc">:</span> <span class="dv">8</span>, <span class="dv">9</span>), <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">coef</span>(fit)<span class="sc">^</span><span class="dv">2</span>, <span class="dv">0</span>), <span class="at">type =</span> <span class="st">&quot;l&quot;</span>, <span class="at">lwd =</span> <span class="dv">3</span>, <span class="at">col =</span> <span class="st">&quot;red&quot;</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-22-1.png" width="672" /></p>
<p>This analysis demonstrates that by utilizing a Fourier basis and fitting a linear model, R can effectively estimate the coefficients for each note, allowing one to identify the chord based on the magnitudes of these coefficients. Here we just used sine waves but in general case we have sine and cosine waves. The Discrete Fourier Transform (DFT) is a mathematical technique used to analyze the frequency content of a time-series signal. It fits a completely saturated linear model by including both sine and cosine terms for all possible frequencies that the given time series allows based on its sampling rate. In the context of a two-second digitally sampled music segment, the DFT calculates coefficients for both sine and cosine components at various frequencies. The “completely saturated model” means that it includes coefficients for all possible frequencies up to the Nyquist frequency, which is half the sampling rate. For example, if there are a thousand time points in the sampled music, the DFT will include a thousand coefficients in the model, covering a range of frequencies. This comprehensive approach allows the DFT to capture both the sine and cosine components of the signal, providing a detailed representation of its frequency spectrum.</p>
<p>To illustrate, the DFT is applied to the chord data, and the square real components of the resulting transform are plotted.</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="week-04.html#cb266-1" aria-hidden="true" tabindex="-1"></a>a <span class="ot">&lt;-</span> <span class="fu">fft</span>(chord); </span>
<span id="cb266-2"><a href="week-04.html#cb266-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">Re</span>(a)<span class="sc">^</span><span class="dv">2</span>, <span class="at">type =</span> <span class="st">&quot;l&quot;</span>)</span></code></pre></div>
<p><img src="resources/images/Week04_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
<p>The plot shows peaks at specific frequencies, and by back-calculating these frequencies, one can identify the notes C, E, and G—the components of the C major chord. This technique is commonly used in music and sound processing, where engineers analyze the spectrum of sound signals using the DFT, essentially performing a linear model with numerous sine and cosine terms as regressors.</p>
<p>We want to emphasize that the discovery of the Discrete Fourier Transform was a significant breakthrough. The reason people prefer using the Fourier Transform over the linear model is due to a discovery by the renowned statistician Tucci. Tucci found a quick way to perform the Fourier transform, known as the fast Fourier transform, which has become the standard method. It’s notably faster than the linear model, making it the preferred choice for sound engineers dealing with Fourier transform problems.</p>
<p>In conclusion, this section has demonstrated two key points. First, we can fit complex functions easily with just a few lines of code. Second, linear models can handle tasks that may initially seem beyond their scope, such as diagnosing notes in a chord. Both of these tasks are not only possible but also quite straightforward with linear models. The examples presented required only a minimal amount of code, showcasing the effectiveness of these techniques. We hope you’ve enjoyed the class and gained valuable insights. As you continue your learning journey, we recommend exploring techniques for generalizing models, which we only briefly touched upon in this class. Additionally, delving into correlated and longitudinal data is essential, as it introduces a crucial aspect not covered in our discussion of independent and exchangeable data. Understanding how to handle correlations is vital for extending linear models to various important topics.</p>
<p>If you decide to pursue further studies, prioritize generalized linear models and longitudinal multi-level data. These areas will enhance your understanding and application of linear models to diverse scenarios. Thank you for participating in the class, and feel free to follow Jeff Leak and Roger Pang on Twitter for updates on new developments in our data science lab.</p>
</div>
<div id="practical-r-exercises-in-swirl-3" class="section level2" number="4.5">
<h2><span class="header-section-number">4.5</span> Practical R Exercises in swirl</h2>
<p>During this week of the course you should complete the following lessons in the Regression Models swirl course:</p>
<ol style="list-style-type: decimal">
<li>Variance Inflation Factors</li>
<li>Overfitting and Underfitting</li>
<li>Binary Outcomes</li>
<li>Count Outcomes</li>
</ol>
</div>
<div id="week-4-quiz" class="section level2" number="4.6">
<h2><span class="header-section-number">4.6</span> Week 4 Quiz</h2>
<ol style="list-style-type: decimal">
<li><p>Consider the space shuttle data <code>?shuttle</code> in the <code>MASS</code> library. Consider modeling the use of the autolander as the outcome (variable name <code>use</code>). Fit a logistic regression model with autolander (variable auto) use (labeled as “auto” 1) versus not (0) as predicted by wind sign (variable wind). Give the estimated odds ratio for autolander use comparing head winds, labeled as “head” in the variable headwind (numerator) to tail winds (denominator).</p></li>
<li><p>Consider the previous problem. Give the estimated odds ratio for autolander use comparing head winds (numerator) to tail winds (denominator) adjusting for wind strength from the variable magn.</p></li>
<li><p>If you fit a logistic regression model to a binary variable, for example use of the autolander, then fit a logistic regression model for one minus the outcome (not using the autolander) what happens to the coefficients?</p></li>
<li><p>Consider the insect spray data <code>InsectSprays</code>. Fit a Poisson model using spray as a factor level. Report the estimated relative rate comapring spray A (numerator) to spray B (denominator).</p></li>
<li><p>Consider a Poisson glm with an offset, <code>t</code>. So, for example, a model of the form <code>glm(count ~ x + offset(t), family = poisson)</code> where <code>x</code> is a factor variable comparing a treatment (1) to a control (0) and <code>t</code> is the natural log of a monitoring time. What is impact of the coefficient for <code>x</code> if we fit the model <code>glm(count ~ x + offset(t2), family = poisson)</code> where <code>2 &lt;- log(10) + t</code>? In other words, what happens to the coefficients if we change the units of the offset variable. (Note, adding log(10) on the log scale is multiplying by 10 on the original scale.)</p></li>
<li><p>Consider the data below. Using a knot point at 0, fit a linear model that looks like a hockey stick with two lines meeting at x=0. Include an intercept term, x and the knot point term. What is the estimated slope of the line after 0?</p></li>
</ol>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="week-04.html#cb267-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="sc">-</span><span class="dv">5</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb267-2"><a href="week-04.html#cb267-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">5.12</span>, <span class="fl">3.93</span>, <span class="fl">2.67</span>, <span class="fl">1.87</span>, <span class="fl">0.52</span>, <span class="fl">0.08</span>, <span class="fl">0.93</span>, <span class="fl">2.05</span>, <span class="fl">2.54</span>, <span class="fl">3.87</span>, <span class="fl">4.97</span>)</span></code></pre></div>
</div>
<div id="course-project-1" class="section level2" number="4.7">
<h2><span class="header-section-number">4.7</span> Course Project</h2>
<p>You work for Motor Trend, a magazine about the automobile industry. Looking at a data set of a collection of cars, they are interested in exploring the relationship between a set of variables and miles per gallon (MPG) (outcome). They are particularly interested in the following two questions:
* “Is an automatic or manual transmission better for MPG”
* “Quantify the MPG difference between automatic and manual transmissions”</p>
<p><strong>Grading Criteria Overview</strong></p>
<p><em>Peer Grading</em></p>
<ul>
<li>The criteria that your classmates will use to evaluate and grade your work are shown below.</li>
<li>Each criteria is binary: (1 point = criteria met acceptably; 0 points = criteria not met acceptably)</li>
</ul>
<p><em>Criteria</em></p>
<ul>
<li>Did the student interpret the coefficients correctly?</li>
<li>Did the student do some exploratory data analyses?</li>
<li>Did the student fit multiple models and detail their strategy for model selection?</li>
<li>Did the student answer the questions of interest or detail why the question(s) is (are) not answerable?</li>
<li>Did the student do a residual plot and some diagnostics?</li>
<li>Did the student quantify the uncertainty in their conclusions and/or perform an inference correctly?</li>
<li>Was the report brief (about 2 pages long) for the main body of the report and no longer than 5 with supporting appendix of figures?</li>
<li>Did the report include an executive summary?</li>
<li>Was the report done in Rmd (knitr)?</li>
</ul>

</div>
</div>
<hr>
<center> 
  <div class="footer">
      All illustrations <a href="https://creativecommons.org/licenses/by/4.0/">CC-BY. </a>
      <br>
      All other materials <a href= "https://creativecommons.org/licenses/by/4.0/"> CC-BY </a> unless noted otherwise.
  </div>
</center>
            </section>

          </div>
        </div>
      </div>
<a href="week-03.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="about-the-authors.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
